CREATE TABLE "movies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"title" text NOT NULL,
	"original_title" text,
	"tagline" text,
	"overview" text NOT NULL,
	"release_date" date,
	"runtime_minutes" integer,
	"status" text DEFAULT 'released',
	"genres" text[] DEFAULT '{}'::text[] NOT NULL,
	"keywords" text[] DEFAULT '{}'::text[] NOT NULL,
	"languages" text[] DEFAULT '{}'::text[] NOT NULL,
	"countries" text[] DEFAULT '{}'::text[] NOT NULL,
	"directors" text[] DEFAULT '{}'::text[] NOT NULL,
	"writers" text[] DEFAULT '{}'::text[] NOT NULL,
	"cast_members" text[] DEFAULT '{}'::text[] NOT NULL,
	"rating" numeric(3,1),
	"vote_count" integer DEFAULT 0,
	"budget" bigint,
	"revenue" bigint,
	"poster_url" text,
	"backdrop_url" text,
	"trailer_url" text,
	"imdb_id" text,
	"tmdb_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
